name: sgborg
channels:
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - python=3.8
  - requests
  - streamlit
  - numpy
  - rdkit
  - xtb-python
  - pandas
  - matplotlib
  - seaborn
  - py3Dmol
  - deap
  - scikit-learn